### ISSUE TITLE
Filling 8x8 with white leds causes reboot

### ISSUE THREAD

**Issue by M4kI9H7** [203Electronics/MatrixOS#26]
To reproduce:
While connected to PC with USB
Brightness level: <s>100</s> 45 or more
Use LIGHT Mode, with white LEDs.

Effect:
Matrix Pro reboots, and becomes unresponsive.
Requires disconnecting and connecting again to recover from this state.

Maybe Matrix Pro couldn't draw too much power from USB?

**Comment by EmilyMusicOfficial** [comment]
Happens to me too, probably that it cant drow enough power yeah

**Comment by 203Null** [comment]
It can totally draw the power to run in full brightness and it is designed to. The issues is that your PC might not be. 

When the device is sinking too much current, your PC might not be able to sustain a 5V output via USB and will start dropping. When it is dropped too low, the MCU will not be able to operate and become unresponsive. 

The 100% brightness draws around 1A in normal but will draw more under full white LED. This can be fixed by using a split USB input or using a powered USB HUB to supply more power for Matrix.

**Comment by 203Null** [comment]
I might reduce the 100% rating if the current one is not as stable for most case.

This is also a special boot combination that drops the Matrix's brightness to minimal to ensure safe boot on lower power capable host.

![image](https://user-images.githubusercontent.com/19933093/214824001-6e513ed1-529b-4765-be77-098eef7ccadf.jpeg)

Note: USB port pointing up. This special combination is not affected by your OS's rotation setting.

**Comment by 203Null** [comment]
Also since the LEDs used in Matrix are smart LED (They maintains their output without host intervention, allow the host to spent CPU resource on more important stuffs)

When SOC got brownouts, the LEDs will not self erase. It need to be physically disconnected from the power source.

**Comment by M4kI9H7** [comment]
When it reboots it plays boot animation, and goes into Mode selection UI - seemingly unresponsive to touchpad or FN.

**Comment by 203Null** [comment]
> When it reboots it plays boot animation, and goes into Mode selection UI - seemingly unresponsive to touchpad or FN.

Coprocessor need to be reseted upon SOC reboot / brownout.
Fixing that in the next patch.

**Comment by 203Null** [comment]
Closing this thread.

Problem 1 - Reset under high brightness:
Matrix Pro V1.1 (Rev B) has two diodes in the serial which causes too much voltage drop to the chip, causing it to reset.
The diode is configured as VBUS -> VLED -> VSOC
This is fixed on Rev C by adding another diode between VBUS and VSOC so there will be less voltage drop

Problem 2 - FIxed by 40eb796
